<?php

/**
 * @file
 * Contains ausy_registration.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ausy_registration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ausy_registration module.
    case 'help.page.ausy_registration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Ausy registration module description') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ausy_registration_theme() {
  return [
    'ausy_registration' => [
      'render element' => 'children',
    ],
  ];
}
